services:
  - type: web
    name: barberia-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py create_superuser_auto
    startCommand: gunicorn BarberiaApp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: BarberiaApp.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .render.com,cortesconhistoria.com.ar,www.cortesconhistoria.com.ar
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@barberia.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: BarberiaAdmin2025!
      - key: DJANGO_SUPERUSER_NOMBRE
        value: Admin
      - key: DJANGO_SUPERUSER_APELLIDO
        value: Barberia
      - key: DJANGO_SUPERUSER_TELEFONO
        value: 1234567890
      - key: CLOUDINARY_CLOUD_NAME
        value: dfkhuibwf
      - key: CLOUDINARY_API_KEY
        value: 857993365988948
      - key: CLOUDINARY_API_SECRET
        value: ccEnjqy6Kj4UYri9U2fsl4gdDfI
    databaseUser: barberia_user
